In [33]:
import numpy as np
import numpy.random
import numpy.linalg
from numpy.linalg import *
from numpy import *

In [88]:
alpha, beta, sigma = [3, 0.2, 0.05] 

# g = metric
def g(x, y): return np.trace(x.T @ y)


def sym(x):
    return 0.5 * (x + x.T)

# P_x Z
def project_tangent_space(x, z):
    return z - x @ (sym(x.T @ z))


def retraction(x, tau):
    return qr(x + tau)[0]

# A = symmetric
A = np.array([[1, 2], [2, 1]])

# N = diagonal
N = np.diag([1, 2])

    
def cost_function(x):
    return np.trace(x.T @ A @ x @ N)
def gradient(x):
    return project_tangent_space(x, 2 * A @ x @ N)

# Tangent space

$$T_X(M) = \{ Z \mid X^T Z + Z^T X = 0 \}$$


In [127]:
def armijo_step(x_cur):
    m = 0
    while True:
        # we choose eta as negative of gradient:
        eta = -1.0 *  gradient(x_cur)
        r = retraction(x_cur, alpha*(beta**m)*eta)
        dot = g((-1.0 * sigma * gradient(x_cur)), ((beta **m) * alpha * eta))
        if cost_function(x_cur) - cost_function(r) >= dot:
            return alpha*(beta**m)
        print("m: %s" % m)
        m += 1

        
def run_gradient_descent_armijo(x0):
    x_cur = x0
    XS = [x_cur]
    YS = [cost_function(x_cur)]
    ETAS = []
    i = 0
    while i <= 10000:
        #eta_k is chosen as -grad f(x_k) which is gradient-related
        eta_k = -1.0 * gradient(x_cur)
        ETAS.append(eta_k)
        # if np.linalg.norm(eta_k) < 1e-4: break
        
        t_k = 1e-3
        # t_k = armijo_step(x_cur)
        x_cur = retraction(x_cur, t_k*eta_k)
        XS.append(x_cur)
        YS.append(cost_function(x_cur))
        i += 1
    return (np.array(XS), np.array(YS), np.array(ETAS))

In [129]:
np.random.seed(0)
begin = retraction(begin, np.zeros(2))
print(begin)
print(begin.T @ begin)

(xs, ys, etas) = run_gradient_descent_armijo(begin)
print("ys: ")
print(ys)
print("xs: ")
print(xs[-1])
print("A diagonalized (roughly):")
print(xs[-1].T @ A @ xs[-1])

[[-0.67324134 -0.73942281]
 [-0.73942281  0.67324134]]
[[ 1.00000000e+00 -9.44129754e-17]
 [-9.44129754e-17  1.00000000e+00]]
ys: 
[1.00875997 1.00869019 1.00862095 ... 1.         1.         1.        ]
xs: 
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
A diagonalized (roughly):
[[ 3.00000000e+00  2.06514760e-13]
 [ 2.06284647e-13 -1.00000000e+00]]


In [80]:
def random_ortho():
    return qr(np.random.rand(2, 2))[0]
